[project]
name = "mineru-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "mineru-vl-utils>=0.1.8",
    "numpy>=2.3.3",
    "pillow>=11.3.0",
    "pypdfium2>=4.30.0",
]
